//! Emit a `scenario` HJSON from resolved + compiled scenes. `deser-hjson` is
//! deserialize-only, so this is a small hand-written formatter: unquoted keys +
//! JSON-escaped string values + `//` comments (all valid HJSON). Output is
//! **deterministic** (no timestamp) so corpus proofs are byte-stable.

use super::resolver::{ResolvedGlobals, ResolvedScene};

/// A scene with its final compiled prompt + negative (post-LLM or verbatim).
pub struct CompiledScene {
    pub scene: ResolvedScene,
    pub prompt: String,
    pub negative: String,
}

fn q(s: &str) -> String {
    // serde_json gives correct, deterministic escaping for any content.
    serde_json::to_string(s).unwrap_or_else(|_| format!("{s:?}"))
}

/// Render the scenario HJSON. `input_name` and `provider` go into the header
/// comment; both are inputs, so the output stays deterministic.
pub fn emit(globals: &ResolvedGlobals, scenes: &[CompiledScene], input_name: &str, provider: &str) -> String {
    let mut o = String::new();
    o.push_str(&format!("// Generated by: plakat compile {input_name}\n"));
    o.push_str(&format!(
        "// Provider: {provider}  ·  Global model family: {}\n",
        globals.family.label()
    ));
    o.push_str("// Edit freely, then: plakat scenario <this file>\n");
    o.push_str("{\n");

    // ---- global generation parameters ----
    // model / size / scheduler are verbatim user strings — quote+escape them like the
    // other string scalars, or a value such as `size: "1024` (open quote / brace) emits an
    // HJSON value that runs to EOL and makes the whole compiled scenario fail to load.
    if let Some(m) = &globals.model {
        o.push_str(&format!("  model: {}\n", q(m)));
    }
    if let Some(s) = &globals.size {
        o.push_str(&format!("  size: {}\n", q(s)));
    }
    if let Some(n) = globals.steps {
        o.push_str(&format!("  steps: {n}\n"));
    }
    if let Some(g) = globals.guidance {
        o.push_str(&format!("  guidance: {g}\n"));
    }
    if let Some(s) = globals.seed {
        o.push_str(&format!("  seed: {s}\n"));
    }
    if let Some(c) = globals.count {
        o.push_str(&format!("  count: {c}\n"));
    }
    if let Some(s) = &globals.scheduler {
        o.push_str(&format!("  scheduler: {}\n", q(s)));
    }
    if let Some(r) = globals.refine {
        o.push_str(&format!("  refine: {r}\n"));
    }
    if !globals.loras.is_empty() {
        let items: Vec<String> = globals.loras.iter().map(|l| q(l)).collect();
        o.push_str(&format!("  loras: [{}]\n", items.join(", ")));
    }
    if !globals.negative_seeds.trim().is_empty() {
        o.push_str(&format!("  negative: {}\n", q(&globals.negative_seeds)));
    }
    // Prompts are pre-enhanced by compile, so every task opts out of the
    // scenario-time enhancer. `enhancer: auto` satisfies the schema (a missing
    // key/no-LLM still validates); the per-task `enhance: false` does the work.
    o.push_str("  enhancer: auto\n\n");

    // ---- minimal scene/weather axes (scenarios cross scene×weather→tasks) ----
    o.push_str("  scene: [ { name: \"plain\", prompt: \"\" } ]\n");
    o.push_str("  weather: [ { name: \"any\", prompt: \"\" } ]\n\n");

    // ---- tasks (one per compiled scene; skipped scenes are omitted) ----
    o.push_str("  tasks:\n  [\n");
    for cs in scenes {
        let s = &cs.scene;
        o.push_str("    {\n");
        o.push_str(&format!("      name: {}\n", sanitize_name(&s.name)));
        o.push_str("      scene: plain\n");
        o.push_str("      weather: any\n");
        o.push_str("      enhance: false\n");
        if let Some(m) = &s.model_for_family {
            if globals.model.as_deref() != Some(m.as_str()) {
                o.push_str(&format!(
                    "      // note: prompt written for {} ({}); scenario runs the global model\n",
                    m,
                    s.family.label()
                ));
            }
        }
        // A bookart / texture / comic task folds the prompt into its spec block below and ignores the
        // top-level prompt/negative — don't emit them (they'd be dead, and confusing).
        if !matches!(s.task_type.as_deref(), Some("bookart") | Some("texture") | Some("comic")) {
            o.push_str(&format!("      prompt: {}\n", q(&cs.prompt)));
            if !cs.negative.trim().is_empty() {
                o.push_str(&format!("      negative: {}\n", q(&cs.negative)));
            }
        }
        if let Some(seed) = s.seed {
            o.push_str(&format!("      seed: {seed}\n"));
        }
        if let Some(c) = s.count {
            o.push_str(&format!("      count: {c}\n"));
        }
        if let Some(sz) = &s.size {
            o.push_str(&format!("      size: {}\n", q(sz)));
        }
        if let Some(n) = s.steps {
            o.push_str(&format!("      steps: {n}\n"));
        }
        if let Some(g) = s.guidance {
            o.push_str(&format!("      guidance: {g}\n"));
        }
        if let Some(sc) = &s.scheduler {
            o.push_str(&format!("      scheduler: {}\n", q(sc)));
        }
        if let Some(r) = s.refine {
            o.push_str(&format!("      refine: {r}\n"));
        }
        // MAP-4: emit the map directives so a `type: map` block becomes a map task.
        if let Some(t) = &s.task_type {
            o.push_str(&format!("      type: {}\n", q(t)));
        }
        if let Some(v) = &s.map_spec {
            o.push_str(&format!("      map-spec: {}\n", q(v)));
        }
        if let Some(v) = &s.map_style {
            o.push_str(&format!("      map-style: {}\n", q(v)));
        }
        if let Some(v) = &s.map_paint {
            o.push_str(&format!("      map-paint: {v}\n")); // true|false (bool in HJSON)
        }
        if let Some(v) = &s.map_scale {
            o.push_str(&format!("      map-scale: {}\n", q(v)));
        }
        if let Some(v) = &s.map_tiles {
            o.push_str(&format!("      map-tiles: {}\n", q(v)));
        }
        if let Some(v) = &s.map_sd_model {
            o.push_str(&format!("      map-sd-model: {}\n", q(v)));
        }
        if !s.map_sd_lora.is_empty() {
            let items: Vec<String> = s.map_sd_lora.iter().map(|l| q(l)).collect();
            o.push_str(&format!("      map-sd-lora: [{}]\n", items.join(", ")));
        }
        if let Some(v) = &s.map_provider {
            o.push_str(&format!("      map-provider: {}\n", q(v)));
        }
        // 6.1.0 A3: emit the bookart spec block so a `type: bookart` compile block → a bookart task.
        if s.task_type.as_deref() == Some("bookart") {
            o.push_str("      bookart: {\n        spec: {\n");
            if let Some(v) = &s.bookart_origin {
                o.push_str(&format!("          origin: {}\n", q(v)));
            }
            if let Some(v) = &s.bookart_technique {
                o.push_str(&format!("          technique: {}\n", q(v)));
            }
            o.push_str("          ornament: {\n");
            o.push_str(&format!("            type: {}\n", q(s.bookart_type.as_deref().unwrap_or("vignette"))));
            if !cs.prompt.trim().is_empty() {
                o.push_str(&format!("            prompt: {}\n", q(&cs.prompt)));
            }
            o.push_str("          }\n");
            if let Some(v) = &s.bookart_page {
                o.push_str(&format!("          page: {{ size: {} }}\n", q(v)));
            }
            o.push_str("        }\n");
            if let Some(v) = &s.bookart_svg {
                o.push_str(&format!("        svg: {v}\n"));
            }
            o.push_str("      }\n");
        }
        // 6.3.0 B7: emit the texture spec block so a `type: texture` compile block → a texture task. The
        // prose is the material prompt (empty for an image-to-material `texture-from`).
        if s.task_type.as_deref() == Some("texture") {
            o.push_str("      texture: {\n        spec: {\n");
            if !cs.prompt.trim().is_empty() {
                o.push_str(&format!("          material: {}\n", q(&cs.prompt)));
            }
            if let Some(v) = &s.texture_from {
                o.push_str(&format!("          from_image: {}\n", q(v)));
            }
            if let Some(v) = &s.texture_seamless {
                o.push_str(&format!("          seamless: {{ mode: {} }}\n", q(v)));
            }
            if let Some(v) = &s.texture_height {
                o.push_str(&format!("          channels: {{ height: {} }}\n", q(v)));
            }
            if s.texture_size.is_some() || s.texture_upscale.is_some() {
                o.push_str("          page: {");
                if let Some(v) = &s.texture_size {
                    o.push_str(&format!(" size: {v}")); // u32 — unquoted
                }
                if let Some(v) = &s.texture_upscale {
                    o.push_str(&format!(" upscale: {}", q(v)));
                }
                o.push_str(" }\n");
            }
            o.push_str("        }\n      }\n");
        }
        // 6.8.0 P4: emit the comic task block. `comic-spec-file` points at a full ComicSpec; otherwise the
        // prose (if any) becomes a single-panel page.
        if s.task_type.as_deref() == Some("comic") {
            if let Some(v) = &s.comic_spec_file {
                o.push_str(&format!("      comic: {{ spec_file: {} }}\n", q(v)));
            } else {
                o.push_str("      comic: {\n        spec: {\n          panels: [\n");
                o.push_str(&format!("            {{ scene: {} }}\n", q(&cs.prompt)));
                o.push_str("          ]\n        }\n      }\n");
            }
        }
        o.push_str("    }\n");
    }
    o.push_str("  ]\n");
    o.push_str("}\n");
    o
}

/// Task names must be a single token (scenario uses them as ids). Replace any
/// run of non-alphanumeric chars with one underscore.
fn sanitize_name(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut last_us = false;
    for c in name.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_lowercase());
            last_us = false;
        } else if !last_us {
            out.push('_');
            last_us = true;
        }
    }
    let trimmed = out.trim_matches('_').to_string();
    if trimmed.is_empty() { "scene".into() } else { trimmed }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compile::ModelFamily;

    fn compiled() -> (ResolvedGlobals, Vec<CompiledScene>) {
        let globals = ResolvedGlobals {
            model: Some("sdxl".into()),
            family: ModelFamily::Sdxl,
            steps: Some(30),
            negative_seeds: "blurry, watermark".into(),
            ..Default::default()
        };
        let scene = ResolvedScene {
            name: "Tundra Rider".into(),
            seed: Some(42),
            family: ModelFamily::Sdxl,
            ..Default::default()
        };
        let cs = CompiledScene {
            scene,
            prompt: "a frozen tundra, lone rider, aurora".into(),
            negative: "blurry, watermark, daylight".into(),
        };
        (globals, vec![cs])
    }

    #[test]
    fn emits_parseable_deterministic_hjson() {
        let (g, scenes) = compiled();
        let a = emit(&g, &scenes, "prompts.txt", "deepseek");
        let b = emit(&g, &scenes, "prompts.txt", "deepseek");
        assert_eq!(a, b, "deterministic (no timestamp)");
        assert!(a.contains("name: tundra_rider"), "name sanitized");
        assert!(a.contains("enhance: false"));
        assert!(a.contains("seed: 42"));
        assert!(a.contains(r#"model: "sdxl""#), "string scalars are quoted");
        // It must round-trip through the same HJSON parser scenario uses.
        let _: serde_json::Value = deser_hjson::from_str(&a)
            .unwrap_or_else(|e| panic!("emitted HJSON did not parse: {e}\n---\n{a}"));
    }

    #[test]
    fn hostile_scalar_values_stay_parseable() {
        // A `size`/`scheduler`/`model` value with an unbalanced quote or brace used to emit
        // an HJSON value that ran to EOL and broke the whole file. Quoting keeps it valid.
        let (mut g, scenes) = compiled();
        g.size = Some(r#"1024","injected": true,"x": "#.into());
        g.scheduler = Some("{euler".into());
        let out = emit(&g, &scenes, "prompts.txt", "deepseek");
        let v: serde_json::Value = deser_hjson::from_str(&out)
            .unwrap_or_else(|e| panic!("hostile scalars broke HJSON: {e}\n---\n{out}"));
        // The value is a single string, not a smuggled second key.
        assert!(v.get("injected").is_none(), "no key injection via the size value");
        assert_eq!(v["scheduler"], "{euler", "scheduler kept as a literal string");
    }

    #[test]
    fn sanitizes_names() {
        assert_eq!(sanitize_name("Lady Mireth!"), "lady_mireth");
        assert_eq!(sanitize_name("ch01_establishing"), "ch01_establishing");
        assert_eq!(sanitize_name("***"), "scene");
    }
}
